### ISSUE TITLE
Allow generating sub-classed Promise

### ISSUE THREAD

**Issue by dfahlander** [tc39/proposal-async-await#73] opened 2015-11-12 12:02 UTC
I've understood that the discussion in #40 was not accepted. However this is a shame beause promises like WinJS' with cancellation support will break when using async / await. So also with Dexie.Promises that maintains async-static data (https://github.com/dfahlander/Dexie.js/wiki/Promise.PSD).

Now, since ES2015 spec clarifies that Promise should be able to sub-class, it would be great if async/await could respect a sub classed promise and rather than hard-coding the creation of the built-in Promise, generate the a custom promise as suggested in #40, but only if the async function's first await call will yield a Promise that is sub classed from the built-in Promise.

**This would save all Promise vendors like Q, WinJS, Dexie, etc from not being able to work with async/await. We could start sub classing Promise to gain the lovely async/await support and still support custom features such as [cancellation](https://msdn.microsoft.com/en-us/library/windows/apps/br211667.aspx) and [PSD](https://github.com/dfahlander/Dexie.js/wiki/Promise.PSD).**

Either it could be implemented as returning (yielded Promise).then(res => {}, err => {}), as suggested in #40, or it could do new (yielded Promise).constructor((resolve, reject) => {...}); 

For await*, do in the same manner - if first item in the provided Promise-array is a sub classed Promise, do (subPromise).constructor.all() instead of Promise.all().

David

**Comment by bterlson** [comment] 2015-11-12 20:28
Closing this as it seems like a duplicate of #40.

(Note that await\* is not part of the proposal).

**Closed as completed by bterlson** 2015-11-12 20:28 UTC
